version: '1.0'
services:
  app:
    build: .
    depends_on:
      - mysql
      - postgresdb

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3307"
    environment:  # MySQL requires environment variables to set passwords, etc.
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: target
    volumes:
      - mysql-data:/var/lib/mysql

  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:  # Postgres also requires environment variables for initial setup
      POSTGRES_DB: target
      POSTGRES_PASSWORD: password
    volumes:
      - postgresdb-data:/var/lib/postgresql/data

  avantgraph:
    image: lsiecker/avantgraph:latest
    ports:
      - "7689:7689"
    privileged: true
    ulimits: 
      memlock: "1024000"
    command: ["ag-server", "--listen", "0.0.0.0:7689", "output_graph/"]
    restart: "on-failure"
    volumes:
      - avantgraph-data:/home/me

volumes:
  mysql-data:
  postgresdb-data:
  avantgraph-data:
